development: &base
  0:
    system: "fandom"
    friendly: "Fandom(s)"
  1: 
    system: "character"
    friendly: "Character(s)"
  2: 
    system: "primary_pairing"
    friendly: "Primary Pairing(s)"
  3: 
    system: "secondary_pairing"
    friendly: "Secondary Pairing(s)"
  4: 
    system: "theme"
    friendly: "Theme(s)"
  5:
    system: "content"
    friendly: "Warning(s)"
test:
 <<: *base

production:
  <<: *base
